FROM node:alpine as build-stage

WORKDIR /usr/src/app
COPY tictactoe/package*.json ./
RUN npm install

RUN npm run build

FROM nginx:alpine

COPY --from=build-stage /usr/src/app/build/ /usr/share/nginx/html
