FROM node:alpine as build-stage

COPY jsnhongcom/ /usr/src/app/
WORKDIR /usr/src/app
RUN apk add --no-cache python3
RUN npm install

RUN npm run build

FROM nginx:alpine

COPY --from=build-stage /usr/src/app/dist/ /usr/share/nginx/html/
