FROM node:alpine as build-stage

COPY tictactoe/* /usr/src/app/
WORKDIR /usr/src/app
RUN npm install

RUN pwd
RUN ls -l
RUN npm run build

FROM nginx:alpine

COPY --from=build-stage /usr/src/app/build/* /usr/share/nginx/html
