version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:
  docker-blog:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - docker/check:
          docker-password: DOCKER_PASS 
          docker-username: DOCKER_USER 
      - docker/build:
          dockerfile: docker/Dockerfile-blog 
          image: jasonhongxyz/blog
          tag: latest
      - docker/push:
          image: jasonhongxyz/blog
          tag: latest
      - add_ssh_keys:
          fingerprints:
          - "21:8d:91:cd:1b:69:af:3e:b1:4a:af:13:24:79:eb:b2"
      - run: |
          ssh-keyscan jasonhong.xyz >> ~/.ssh/known_hosts
          ssh root@jasonhong.xyz \<<'ENDSSH'
          cd website
          git pull
          docker pull jasonhongxyz/blog:latest
          docker compose up -d
          ENDSSH

  docker-tictactoe:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - docker/check:
          docker-password: DOCKER_PASS 
          docker-username: DOCKER_USER 
      - docker/build:
          dockerfile: docker/Dockerfile-tictactoe
          image: jasonhongxyz/tictactoe
          tag: latest
      - docker/push:
          image: jasonhongxyz/tictactoe
          tag: latest
      - add_ssh_keys:
          fingerprints:
          - "21:8d:91:cd:1b:69:af:3e:b1:4a:af:13:24:79:eb:b2"
      - run: |
          ssh-keyscan jasonhong.xyz >> ~/.ssh/known_hosts
          ssh root@jasonhong.xyz \<<'ENDSSH'
          cd website
          git pull
          docker pull jasonhongxyz/tictactoe:latest
          docker compose up -d
          ENDSSH

workflows:
  main:
    jobs:
      - docker-blog
      - docker-tictactoe
