version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:
  docker-blog:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - docker/check:
          docker-password: DOCKER_PASS 
          docker-username: DOCKER_USER 
      - docker/build:
          dockerfile: Dockerfile-blog 
          image: jasonhongxyz/blog
          tag: latest
      - docker/push:
          image: jasonhongxyz/blog
          tag: latest
      - add_ssh_keys:
          fingerprints:
          - "b4:78:c3:4f:8e:fc:d2:87:ae:d6:ce:b2:e7:e0:45:d2"
      - run: ls -la
          

workflows:
  main:
    jobs:
      - docker-blog