version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:
  docker-tictactoe:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - docker/check:
          docker-password: DOCKER_PASS 
          docker-username: DOCKER_USER 
      - docker/build:
          dockerfile: Dockerfile-tictactoe
          image: jasonhongxyz/tictactoe
          tag: latest
      - docker/push:
          image: jasonhongxyz/tictactoe
          tag: latest
      - add_ssh_keys:
          fingerprints:
          - "4a:b3:c4:d3:b2:76:30:d0:1d:20:e9:87:25:80:e8:24"
      - run: |
          ssh-keyscan jsnhong.com >> ~/.ssh/known_hosts
          ssh root@jsnhong.com \<<'ENDSSH'
          cd website
          git pull
          docker pull jasonhongxyz/tictactoe:latest
          docker compose up -d
          ENDSSH

  docker-jsnhongcom:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - docker/check:
          docker-password: DOCKER_PASS 
          docker-username: DOCKER_USER 
      - docker/build:
          dockerfile: Dockerfile-jsnhongcom
          image: jasonhongxyz/jsnhongcom
          tag: latest
      - docker/push:
          image: jasonhongxyz/jsnhongcom
          tag: latest
      - add_ssh_keys:
          fingerprints:
          - "4a:b3:c4:d3:b2:76:30:d0:1d:20:e9:87:25:80:e8:24"
      - run: |
          ssh-keyscan jsnhong.com >> ~/.ssh/known_hosts
          ssh root@jsnhong.com \<<'ENDSSH'
          cd website
          git pull
          docker pull jasonhongxyz/jsnhongcom:latest
          docker compose up -d
          ENDSSH
workflows:
  main:
    jobs:
      - docker-tictactoe
      - docker-jsnhongcom
