version: 2.1

orbs:
  docker: circleci/docker@1.7.0

workflows:
    example-workflow:
      jobs:
        - docker/publish:
            image: blog 
            docker-password: DOCKER_PASS 
            docker-username: DOCKER_USER 
            deploy: true 
            lint-dockerfile: true 
            remote-docker-dlc: false 
            treat-warnings-as-errors: false 
            update-description: false 
            use-docker-credentials-store: false 
            use-remote-docker: false 
            dockerfile: Dockerfile-blog 