version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:
  docker-blog:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - docker/build:
          dockerfile: Dockerfile-blog 
          image: blog 

workflows:
  example-workflow:
    jobs:
      - docker-blog