version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:
  docker-blog:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - checkout
      - docker/check:
          docker-password: DOCKER_PASS 
          docker-username: DOCKER_USER 
      - docker/build:
          dockerfile: Dockerfile-blog 
          image: jasonhongxyz/blog 

workflows:
  main:
    jobs:
      - docker-blog